name: muslim_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  http: 1.2.0
  flutter_screenutil: 5.9.0
  intl: 0.19.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
        - asset: assets/fonts/poppins/Poppins-Light.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
    - family: Amiri
      fonts: 
        - asset: assets/fonts/amiri/Amiri-Bold.ttf
        - asset: assets/fonts/amiri/Amiri-BoldItalic.ttf
        - asset: assets/fonts/amiri/Amiri-Italic.ttf
        - asset: assets/fonts/amiri/Amiri-Regular.ttf
  uses-material-design: true

